#pragma once

#include "Core/Forming/StretchBendingEvaluationStatus.h"

// =====================================================
// STRETCH-BENDING EVALUATION RESULT
//
// Stores calculated section, material, strain, force,
// moment, and feasibility values.
//
// This result does not modify manufacturing geometry.
// =====================================================

struct StretchBendingEvaluationResult
{
    StretchBendingEvaluationStatus status =
        StretchBendingEvaluationStatus::NotEvaluated;

    // ===== Section properties =====

    double innerDiameter =
        0.0;

    double area =
        0.0;

    double secondMomentArea =
        0.0;

    // ===== Material values =====

    double yieldStrain =
        0.0;

    double yieldCurvature =
        0.0;

    // ===== Geometry =====

    double targetCurvature =
        0.0;

    double targetTorsion =
        0.0;

    double targetArcLength =
        0.0;

    // ===== Strain calculation =====

    // ?b = ?D/2
    double bendingStrain =
        0.0;

    // ?0
    double axialStretchStrain =
        0.0;

    double innerWallStrain =
        0.0;

    double outerWallStrain =
        0.0;

    double minimumRequiredAxialStrain =
        0.0;

    double maximumAllowedAxialStrain =
        0.0;

    // Recommended center value inside the feasible
// axial-strain interval.
    double recommendedAxialStrain =
        0.0;

    // Width of the available axial-strain interval.
    double axialStrainRange =
        0.0;

    // ===== Machine / force values =====

    // T = E A ?0
    double axialTension =
        0.0;

    // M = E I ?
    double elasticBendingMoment =
        0.0;
    // Tensions corresponding to the feasible axial-strain
// interval:
//
//     T = E * A * epsilon_0
    double minimumRequiredTension =
        0.0;

    double maximumAllowedTension =
        0.0;

    double recommendedTension =
        0.0;

    // Tension generated by the axial strain supplied
// in StretchBendingProcessInput.
    double commandedTension =
        0.0;
    // ===== Margins =====

    double innerCompressionMargin =
        0.0;

    double outerStrainMargin =
        0.0;

    // ===== Flags =====

    bool inputValid =
        false;

    bool geometryFeasible =
        false;

    bool aboveYield =
        false;

    bool innerWallSafe =
        false;

    bool outerWallSafe =
        false;

    bool valid =
        false;
    bool commandedStrainInsideRecommendedRange =
        false;

    void clear()
    {
        status =
            StretchBendingEvaluationStatus::NotEvaluated;

        innerDiameter = 0.0;
        area = 0.0;
        secondMomentArea = 0.0;

        yieldStrain = 0.0;
        yieldCurvature = 0.0;

        targetCurvature = 0.0;
        targetTorsion = 0.0;
        targetArcLength = 0.0;

        bendingStrain = 0.0;
        axialStretchStrain = 0.0;

        innerWallStrain = 0.0;
        outerWallStrain = 0.0;

        minimumRequiredAxialStrain = 0.0;
        maximumAllowedAxialStrain = 0.0;

        axialTension = 0.0;
        elasticBendingMoment = 0.0;

        innerCompressionMargin = 0.0;
        outerStrainMargin = 0.0;
         
        inputValid = false;
        geometryFeasible = false;
        aboveYield = false;
        innerWallSafe = false;
        outerWallSafe = false;
        recommendedAxialStrain =
            0.0;

        axialStrainRange =
            0.0;

        minimumRequiredTension =
            0.0;

        maximumAllowedTension =
            0.0;

        recommendedTension =
            0.0;

        commandedTension =
            0.0;
        commandedStrainInsideRecommendedRange =
            false;
        valid = false;
    }
};