#pragma once

#include <cmath>

// =====================================================
// STRETCH-HELIX WRAPPING KINEMATICS
//
// Derived geometric/machine quantities for a cylindrical
// helix generated by axial translation plus rotation.
//
// This structure contains no playback/contact state.
// =====================================================

struct StretchHelixWrappingKinematics
{
    // Centerline radius of the formed workpiece.
    double centerlineRadius =
        0.0;

    // Axial advance per full revolution.
    double pitch =
        0.0;

    // Helix rise parameter:
    //
    //     b = P / (2*pi)
    double helixRisePerRadian =
        0.0;

    // Centerline curvature.
    double curvature =
        0.0;

    // Centerline torsion.
    //
    // Sign represents helix handedness.
    double torsion =
        0.0;

    // Helix angle relative to circumferential direction.
    double helixAngle =
        0.0;

    // Centerline length required for one revolution.
    double arcLengthPerRevolution =
        0.0;

    bool valid =
        false;

    void clear()
    {
        centerlineRadius = 0.0;
        pitch = 0.0;
        helixRisePerRadian = 0.0;

        curvature = 0.0;
        torsion = 0.0;

        helixAngle = 0.0;
        arcLengthPerRevolution = 0.0;

        valid = false;
    }
};